# Setup
title: Gabriel Lacroix
tagline: |
  A blog about the small things that keep me awake at night thinking<br>
  A website about life, music and terminals<br>
  A digital garden for the mysteries and wonders of reality
url: "https://www.gabriellacroix.com"
baseurl: ""
permalink: none

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

collections:
  pages:
    output: true
    permalink: /:path
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  - scope:
      path: ""
      type: notes
    values:
      layout: "note"

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-EK9QFQ0XHY

last-modified-at:
  date-format: '%Y-%m-%d'

# Specify the author for blog posts
author:
  name: Gabriel Lacroix
  url: https://twitter.com/gadiguibou
  email: lacroixgabriel@gmail.com

timezone: America/Montreal