# Setup
title: Gabriel Lacroix
tagline: A blog about all the small things that keep me thinking
url: "https://www.gabriellacroix.com"
paginate: 1
baseurl: ""
permalink: pretty

# Gems
# TODO: Add "jekyll-seo-tag"
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-NT982EZNTC

# Specify the author for blog posts
author:
  name: Gabriel Lacroix
  url: https://twitter.com/gadiguibou
  email: lacroixgabriel@gmail.com

# Custom vars
version: 3.0.0

header_pages:
  Home: "/"
  About: "/about"
  Archive: "/archive"
  Feed: "/atom.xml"
